# Generated by Django 4.0.6 on 2022-08-13 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('updatedAt', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
    ]
